FROM alpine:latest

ENV TZ Asia/Shanghai

ENV S6_VER v1.22.1.0

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories \ 
  && wget https://github.com/just-containers/s6-overlay/releases/download/$S6_VER/s6-overlay-amd64.tar.gz \
  && tar xvzf s6-overlay-amd64.tar.gz -C / \
  && rm -rf s6-overlay-amd64.tar.gz \
  && apk del --no-cache curl

ENTRYPOINT ["/init"]
