# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: http://www.jhipster.tech/profiles/
# More information on configuration properties: http://www.jhipster.tech/common-application-properties/
# ===================================================================

spring:
    datasource:
        url: jdbc:mysql://mysql-mysqlha-0.mysql-mysqlha:3306/mg_voice?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
        username: root
        password: zaq1@WSX

fdfs:
    # FastDFS的外网访问路径
    web-server-url: http://fastdfs:888
