# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: http://www.jhipster.tech/profiles/
# More information on configuration properties: http://www.jhipster.tech/common-application-properties/
# ===================================================================

logging:
    level:
        ROOT: ERROR
        com.haocang: ERROR
        io.github.jhipster: ERROR

spring:
    datasource:
        url: jdbc:mysql://10.240.1.32:3306/mg_base?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: zaq1@WSX

fdfs: 
  # TrackerList参数，支持多个
  tracker-list:        
   - 10.240.1.33:22122
  web-server-url: http://10.240.1.34:80
  port: 80
        

ffmpeg:
    path: /root/ffmpeg/ffmpeg
