---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: 192.168.2.30/mango-11f/gateway:1.0.0.0013-01
          ports:
            - containerPort: 8080
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod,swagger
          - name: SECURITY_USER_NAME
            value: admin
          - name: SECURITY_USER_PASSWORD
            value: admin
          - name: JHIPSTER_REGISTRY_PASSWORD
            value: admin
          - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
            value: http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
          - name: SPRING_CLOUD_CONFIG_URI
            value: http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: gateway
  type: NodePort
