---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: job-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: job
  template:
    metadata:
      labels:
        app: job
    spec:
      containers:
        - name: job
          image: 192.168.2.30/mango-11f/job:1.0.0.0001-01
          ports:
            - containerPort: 8160
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod,swagger
          - name: SECURITY_USER_NAME
            value: admin
          - name: SECURITY_USER_PASSWORD
            value: admin
          - name: JHIPSTER_REGISTRY_PASSWORD
            value: admin
          - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
            value: http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
          - name: SPRING_CLOUD_CONFIG_URI
            value: http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config

---
apiVersion: v1
kind: Service
metadata:
  name: job
spec:
  ports:
    - port: 8160
      targetPort: 8160
      nodePort: 28160
  selector:
    app: job
  type: NodePort
