---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: loong-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loong
  template:
    metadata:
      labels:
        app: loong
    spec:
      containers:
        - name: loong
          image: 192.168.2.30/mango-11f/loong:1.0.0.0030_6
          ports:
            - containerPort: 8090
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod,swagger
          - name: SECURITY_USER_NAME
            value: admin
          - name: SECURITY_USER_PASSWORD
            value: admin
          - name: JHIPSTER_REGISTRY_PASSWORD
            value: admin
          - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
            value: http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
          - name: SPRING_CLOUD_CONFIG_URI
            value: http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config

---
apiVersion: v1
kind: Service
metadata:
  name: loong
spec:
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 28090
  selector:
    app: loong
  type: NodePort
