apiVersion: v1
kind: Service
metadata:
  name: fdfs-svc
  labels:
    app: fdfs-svc
spec:
  ports:
  - port: 22122
    name: tracker
    targetPort: 22122
  - port: 23000
    name: storage
    targetPort: 23000
  - port: 8888
    name: nginx
    targetPort: 8888
  type: NodePort
  selector:
    app: fdfs-pod

---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: fdfs
  namespace: default
spec:
  serviceName: fdfs-svc
  replicas: 2
  selector:
    matchLabels:
      app: fdfs-pod
  template:
    metadata:
      labels:
        app: fdfs-pod
    spec:
      # serviceAccount: nfs-client-provisioner 
      containers:
      - name: tracker
        imagePullPolicy: Always  # IfNotPresent
        image: 192.168.0.75/kubernetes/fdfs:5.11
        ports:
        - containerPort: 22122
          name: tracker
        env:
        - name : TRACKERSERVER
          value: "fdfs-0.fdfs-svc.default.svc fdfs-1.fdfs-svc.default.svc"
        - name: FASTDFS_MODE
          value: tracker
        command:
        - sh
        - -c
        - /usr/bin/run.sh
        readinessProbe:
          exec:
            command:
            - /usr/bin/fdfsOK.sh
            - status
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - /usr/bin/fdfsOK.sh
            - monitor
          initialDelaySeconds: 90
          periodSeconds: 30

      - name: storage
        imagePullPolicy: Always  # IfNotPresent
        image: 192.168.0.75/kubernetes/fdfs:5.11
        ports:
        - containerPort: 8888
          name: storage
        env:
        - name : TRACKERSERVER
          value: "fdfs-0.fdfs-svc.default.svc fdfs-1.fdfs-svc.default.svc"
        - name: FASTDFS_MODE
          value: storage 
        command:
        - sh
        - -c
        - /usr/bin/run.sh
        #readinessProbe:
        #  exec:
        #    command:
        #    - /usr/bin/fdfsOK.sh
        #    - status
        #  initialDelaySeconds: 5
        #  periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - /usr/bin/fdfsOK.sh
            - monitor
          initialDelaySeconds: 90
          periodSeconds: 30
        volumeMounts:
        - name: data
          mountPath: /data/storage

      - name: nginx
        imagePullPolicy: Always  # IfNotPresent
        image: 192.168.0.75/kubernetes/fdfs:5.11
        ports:
        - containerPort: 8888
          name: nginx
        env:
        - name : TRACKERSERVER
          value: "fdfs-0.fdfs-svc.default.svc fdfs-1.fdfs-svc.default.svc"
        - name: FASTDFS_MODE
          value: nginx
        command:
        - sh
        - -c
        - /usr/bin/run.sh
        #readinessProbe:
        #  exec:
        #    command:
        #    - /usr/bin/fdfsOK.sh
        #    - status
        #  initialDelaySeconds: 5
        #  periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - /usr/bin/fdfsOK.sh
            - monitor
          initialDelaySeconds: 90
          periodSeconds: 30
        volumeMounts:
        - name: data
          mountPath: /data/storage
      securityContext:
        runAsUser: 1000
        fsGroup: 1000

  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: "100Gi"
      storageClassName: "nfs-example"
