---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "hazelcast-config"
  labels:
    app: "hazelcast"
data:
  hazelcast.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.9.xsd"
                   xmlns="http://www.hazelcast.com/schema/config"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <group>
        <name>mango-prod</name>
        <password>dev-pass</password>
      </group>
      <properties>
        <property name="hazelcast.discovery.enabled">true</property>
      </properties>
      <network>
        <join>
          <multicast enabled="false"/>
          <tcp-ip enabled="false" />
          <discovery-strategies>
            <discovery-strategy enabled="true" class="com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy">
            </discovery-strategy>
          </discovery-strategies>
        </join>
      </network>
    </hazelcast>

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: "hazelcast-sa"
  labels:
    app: "hazelcast"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "hazelcast-rbac"
  labels:
    app: "hazelcast"
subjects:
- kind: ServiceAccount
  name: "hazelcast-sa"
  namespace: default
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-svc
  labels:
    app: "hazelcast" 
spec:
  type: ClusterIP
  ports:
    - port: 5701
      targetPort: 5701
      protocol: TCP
      name: hzport
  selector:
    app: hazelcast

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "hazelcast"
  labels:
    app: "hazelcast"
spec:
  selector:
    matchLabels:
      app: "hazelcast"
  replicas: 1
  template:
    metadata:
      labels:
        app: "hazelcast"
    spec:
      serviceAccountName: "hazelcast-sa"
      affinity:      
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 3
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - hazelcast
                - key: release
                  operator: In
                  values:
                  - "hazelcast"
              topologyKey: kubernetes.io/hostname
      containers:
        - name: hazelcast-pod
          image: 192.168.0.75/kubernetes/hazelcast-kubernetes:3.9.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5701
          livenessProbe:
            exec:
              command:
              - "./liveness.sh"
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
              - "./readiness.sh"
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
          env:
          - name: HAZELCAST_KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HAZELCAST_KUBERNETES_SERVICE_NAME
            value: hazelcast-svc
          - name: MIN_HEAP_SIZE
            value: 128m
          - name: MAX_HEAP_SIZE
            value: 256m
          - name: JAVA_OPTS
            value: 
          - name: HZ_DATA
            value: /data/hazelcast
          volumeMounts:
            - name: "hazelcast-conf"
              mountPath: /data/hazelcast
          resources:
            limits:
              cpu: 500m
              memory: 768Mi
            requests:
              cpu: 500m
              memory: 576Mi
      volumes:
      - name: "hazelcast-conf"
        configMap:
          name: "hazelcast-config"
          defaultMode: 0744
