apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "hbase.name" . }}-hbase-master
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/hbase-configmap.yaml") . | sha256sum }}
  labels:
    app: {{ template "hbase.name" . }} 
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: hbase-master
spec:
  serviceName: {{ template "hbase.name" . }}-hbase-master
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "hbase.name" . }}
        release: {{ .Release.Name }}
        component: hbase-master
    spec:
      affinity:
      requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app:  {{ template "hbase.name" . }}
                release: {{ .Release.Name | quote }}
                component: hbase-master
      terminationGracePeriodSeconds: 0
      containers:
      - name: hbase-master
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy  }}
        command:
        - "/bin/bash"
        - "/tmp/hbase-config/bootstrap.sh"
        - "-d"
        resources:
{{ toYaml .Values.hbase.resources | indent 10 }}
        #readinessProbe:
        #  httpGet:
        #    path: /
        #    port: 16010
        #  initialDelaySeconds: 30
        #  timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 16010
          initialDelaySeconds: 30
          timeoutSeconds: 5
        volumeMounts:
        - name: hbase-config
          mountPath: /tmp/hbase-config
      volumes:
      - name: hbase-config
        configMap:
          name: {{ template "hbase.name" . }}-hbase-configmap
