# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# More information on profiles: http://www.jhipster.tech/profiles/
# More information on configuration properties: http://www.jhipster.tech/common-application-properties/
# ===================================================================

#server: # 此处端口仅作参考，用于说明此模块的端口范围，不能直接在此指定，否则多实例情况下使用同一端口会冲突
#    port: 8020

spring:
    application:
        name: uaa
        
eureka:
    client:
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/

application:
    # hazelcast缓存集群分组名（局域网内项目唯一，避免多个项目的缓存自动组网）
    hazelcast-groupname: mango-prod
