apiVersion: v1
kind: Service
metadata:
  name: fastdfs-tracker-svc
  labels:
    app: fastdfs-tracker-svc
spec:
  ports:
  - port: 22122
    name: tracker
  selector:
    app: fastdfs-tracker

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fastdfs-tracker
spec:
  serviceName: fastdfs-tracker-svc
  replicas: 2
  selector:
    matchLabels:
      app: fastdfs-tracker
  template:
    metadata:
      labels:
        app: fastdfs-tracker
    spec:
      containers:
      - name: tracker
        image: 192.168.2.30/kubernetes/fastdfs:5.11
        env:
        - name: FASTDFS_MODE
          value: tracker
        - name: STORAGE_SERVER_NUM
          value: '3'
        ports:
        - containerPort: 22122
          name: tracker
        readinessProbe:
          exec:
            command:
            - /usr/bin/fdfsOK.sh
            - status
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - /usr/bin/fdfsOK.sh
            - monitor
          initialDelaySeconds: 90
          periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: fastdfs-storage-svc
  labels:
    app: fastdfs-storage-svc
spec:
  ports:
  - port: 8888
    name: nginx
    nodePort: 28888
  type: NodePort
  selector:
    app: fastdfs-storage

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fastdfs-storage
spec:
  serviceName: fastdfs-storage-svc
  replicas: 3
  selector:
    matchLabels:
      app: fastdfs-storage
  template:
    metadata:
      labels:
        app: fastdfs-storage
    spec:
      containers:
      - name: storage
        image: 192.168.2.30/kubernetes/fastdfs:5.11
        env:
        - name: FASTDFS_MODE
          value: "storage"
        - name: TRACKER_SERVER_NUM
          value: '2'
        ports:
        - containerPort: 23000
          name: storage
        - containerPort: 8888
          name: nginx
        readinessProbe:
          exec:
            command:
            - /usr/bin/fdfsOK.sh
            - status
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - /usr/bin/fdfsOK.sh
            - monitor
          initialDelaySeconds: 90
          periodSeconds: 30
        volumeMounts:
        - name: data
          mountPath: /data/storage
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteMany"]
      storageClassName: "nfs-expample"
      resources:
        requests:
          storage: 100Gi
