# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: http://www.jhipster.tech/profiles/
# More information on configuration properties: http://www.jhipster.tech/common-application-properties/
# ===================================================================

logging:
    level:
        ROOT: ERROR
        com.hc: ERROR
        io.github.jhipster: ERROR

spring:
    datasource:
        url: jdbc:mysql://10.240.1.32:3306/loong?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
        username: root
        password: zaq1@WSX

application:
    tag-key: QoD
    tag-value: U
    opentsdb-url: http://10.240.1.37:14242



        
